apiVersion: apps/v1
kind: Deployment

metadata:
  name: streamlit

spec:
  replicas: {{ .Values.streamlit.replicaCount }}

  selector:
    matchLabels:
      app: streamlit

  template:
    metadata:
      labels:
        app: streamlit

    spec:
      containers:
        - name: streamlit

          image: "{{ .Values.streamlit.image.repository }}:{{ .Values.streamlit.image.tag }}"
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: retail-platform-config
            - secretRef:
                name: retail-secret

          ports:
            - containerPort: 8501

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"