---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: retail-secret
  namespace: retail-platform
spec:
  encryptedData:
    API_KEY: AgAsJVfNG2w5d5MvgT+awv8cK5jbUOFUh15D4O+5avteVkX/d6e+HYiG0UNggDNZEhGs0WTrfQnndViEMEsPuHXtPiW5QpojrR9xG9VWUx4UR2vbPWdUGX8Amo5nmYgPCK6K9xZRNuFulW2vmShMN640tMmmtgpoUkrbKDmEy+b0+C3z4zK89eIOgSTU8WZ3ccLrCutdD/IunjlUIVFLVdoNBLQcNBz1qHYelNBdqCDyZGSN4+qGZ9ZcpxSIXaM7ljcAUYxQ2GY+E0ZkYs1mDBEbdkL5+3Wd3WHQ7F9GP7oDQ3/wzN/p6H80hA7hOjqdx95Dz2vL94h5+/fltu+8yjNxzmb0qQUv4/4a1ge2PAYUqv1ipr5+MmnaIvGO1urCV+nu5yKNKruMI9jJiaN+/ndeetP3RyXO4vHHPUe/rX3QGc101fTLa9H/N4coNrFYi66+Fqt4pvWtnqANqdkuBQUYYW1Xe8tMaKKR1LBOfGyJevLNwAol/21jAgyeVUAIy4Q/4HH0LbimUhUKnVFvoTVbjxdfJy6J5QEEq56nW6jqUICgNjL5VAlwEO0vCXrA9dlXQ2OZcqRA2fqWCObLfczFcA5gIw/viBpWMU4Jzo9lHCHGkJVRJGb9fi1uDVGxyeOCCKhBV7EFTiM9bdXY3pfEl05rQWQaHEvcrPOcWREl/veitwYnBv4VKyOQ1GqTGN4/Z18qaDe7v7Bf8g==
    REDIS_PASSWORD: AgCFtk8prTGhXUovXB57vTrjKxoPamiIdrNBPr8jsdDHG/gQ1DOR7w9R0Zeh/2SxFV3MtlQi3Otwzy3OO/3HQk8LX2g9SqNfRPZPMRK0goCG96X8StY3aFMzq7CBGSeAdhsCFPR/NDNjovZslxGiFlRelkl8KUSamM3y2W1Vst/KTBpZg2GL/KQcgPIi8IPPgH5Bg6j/qhlG6Ydb7PTfbH0RhEn/e8pVs+XfN58GfWW0YmNuT0cOfnJiVHCMMUrCHmyGBUrmh9C4FAqSbhSQR7Nw+3ZYviHXkg/tf4OkTkSirxYmIsUxPfYZrPf9GLWvGPyMb8RFhZ5pgeGoL2aOjkIZo1Wo/siBGMoh/NblMo0biHi1HC47JC4YiRRUL4yf8/1TU1DxqkP+MGLx6iSD0anVkK/2XksfNKA1GhBwmaH2mAroyJkDvuSnw7MRcjdTLkcYcDXdS7Vy4LsTd3pmaZ3Zsei9SYmHibnIp39vSyYRuZZLuDtKoYcFjzsnGJOMiZFLsIyRu5qZbvdUFfsbMzhZRjJ++xuUyZv1xFUzAj8q+H3+6F5OmG0avzAZ5ZRuityZ6Ocp92HfuVRNNZ/lPkT5wKLaC+sJtHwyPgD+umK5ZkUNG34TxL2gforFoVXvUxAh17vTFK6YOnN4FX58AaGFvLj8HuV20/t4hUwqW7TxSf6iQAYjZMEaw1V7yQYXGLzKdkie0Wyi1/0uwS3i3aA=
  template:
    metadata:
      name: retail-secret
      namespace: retail-platform
    type: Opaque
